"""Generate initial raw and daily schema models

Revision ID: 551f95c6df14
Revises: 
Create Date: 2025-06-06 13:11:37.682899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '551f95c6df14'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS daily_schema")
    op.create_table('raw__daily_metrics',
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=False),
    sa.Column('temperature_2m_max_in_C', sa.Float(), nullable=False),
    sa.Column('temperature_2m_min_in_C', sa.Float(), nullable=False),
    sa.Column('daylight_duration_in_s', sa.Float(), nullable=False),
    sa.Column('uv_index_max', sa.Float(), nullable=False),
    sa.Column('precipatition_sum_in_mm', sa.Float(), nullable=False),
    sa.Column('precipatition_hours_in_s', sa.Float(), nullable=False),
    sa.Column('precipatition_probability_max_in_p', sa.Float(), nullable=False),
    sa.Column('wind_speed_10m_max_in_kmph', sa.Float(), nullable=False),
    sa.Column('wind_direction_10m_dominant_in_degree', sa.Integer(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('longitude', 'latitude', 'measurement_date'),
    schema='raw_schema'
    )
    op.create_table('daily__measurement_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_name', sa.String(), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='daily_schema'
    )
    op.create_table('daily__precipitation_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('precipitation_sum', sa.Float(), nullable=False),
    sa.Column('precipitation_length', sa.Float(), nullable=False),
    sa.Column('precipitation_probability_max', sa.Float(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('daily__measurement_context_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['daily__measurement_context_id'], ['daily_schema.daily__measurement_context.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='daily_schema'
    )
    op.create_table('daily__temperature_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature_2m_max', sa.Float(), nullable=False),
    sa.Column('temperature_2m_min', sa.Float(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('daily__measurement_context_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['daily__measurement_context_id'], ['daily_schema.daily__measurement_context.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='daily_schema'
    )
    op.create_table('daily__uv_lights_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daylight_duration', sa.Float(), nullable=False),
    sa.Column('uv_index_max', sa.Float(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('daily__measurement_context_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['daily__measurement_context_id'], ['daily_schema.daily__measurement_context.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='daily_schema'
    )
    op.create_table('daily__wind_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wind_speed_10m_max', sa.Float(), nullable=False),
    sa.Column('wind_direction_10m_dominant', sa.Integer(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('daily__measurement_context_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['daily__measurement_context_id'], ['daily_schema.daily__measurement_context.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='daily_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily__wind_measurements', schema='daily_schema')
    op.drop_table('daily__uv_lights_measurements', schema='daily_schema')
    op.drop_table('daily__temperature_measurements', schema='daily_schema')
    op.drop_table('daily__precipitation_measurements', schema='daily_schema')
    op.drop_table('daily__measurement_context', schema='daily_schema')
    op.drop_table('raw__daily_metrics', schema='raw_schema')
    # ### end Alembic commands ###
