"""Generate initial hourly schema models and add raw__hourly table

Revision ID: 6c8aa5adf29d
Revises: 551f95c6df14
Create Date: 2025-06-12 11:58:37.232687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c8aa5adf29d'
down_revision: Union[str, None] = '551f95c6df14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS hourly_schema")
    op.create_table('hourly__measurement_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_name', sa.String(), nullable=False),
    sa.Column('measurement_date_and_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='hourly_schema'
    )
    op.create_table('hourly__percipitation_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('percipitation', sa.Float(), nullable=False),
    sa.Column('percipitation_probability', sa.Integer(), nullable=False),
    sa.Column('relative_humidity_2m', sa.Integer(), nullable=False),
    sa.Column('hourly_measurement_context_id', sa.Integer(), nullable=True),
    sa.Column('inserted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hourly_measurement_context_id'], ['hourly_schema.hourly__measurement_context.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hourly_schema'
    )
    op.create_table('hourly__soil_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soil_temperature_0cm', sa.Float(), nullable=False),
    sa.Column('soil_temperature_6cm', sa.Float(), nullable=False),
    sa.Column('soil_temperature_18cm', sa.Float(), nullable=False),
    sa.Column('soil_temperature_54cm', sa.Float(), nullable=False),
    sa.Column('soil_moisture_0cm_to_1cm', sa.Float(), nullable=False),
    sa.Column('soil_moisture_1cm_to_3cm', sa.Float(), nullable=False),
    sa.Column('soil_moisture_3cm_to_9cm', sa.Float(), nullable=False),
    sa.Column('soil_moisture_9cm_to_27cm', sa.Float(), nullable=False),
    sa.Column('soil_moisture_27cm_to_81cm', sa.Float(), nullable=False),
    sa.Column('hourly_measurement_context_id', sa.Integer(), nullable=True),
    sa.Column('inserted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hourly_measurement_context_id'], ['hourly_schema.hourly__measurement_context.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hourly_schema'
    )
    op.create_table('hourly__temperature_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature_2m', sa.Float(), nullable=False),
    sa.Column('temperature_80m', sa.Float(), nullable=False),
    sa.Column('temperature_120m', sa.Float(), nullable=False),
    sa.Column('temperature_180m', sa.Float(), nullable=False),
    sa.Column('hourly_measurement_context_id', sa.Integer(), nullable=True),
    sa.Column('inserted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hourly_measurement_context_id'], ['hourly_schema.hourly__measurement_context.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hourly_schema'
    )
    op.create_table('hourly__visibility_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.Integer(), nullable=False),
    sa.Column('cloud_cover_low', sa.Integer(), nullable=False),
    sa.Column('cloud_cover', sa.Integer(), nullable=False),
    sa.Column('cloud_cover_mid', sa.Integer(), nullable=False),
    sa.Column('cloud_cover_high', sa.Integer(), nullable=False),
    sa.Column('hourly_measurement_context_id', sa.Integer(), nullable=True),
    sa.Column('inserted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hourly_measurement_context_id'], ['hourly_schema.hourly__measurement_context.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hourly_schema'
    )
    op.create_table('hourly__wind_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wind_speed_10m', sa.Float(), nullable=False),
    sa.Column('wind_speed_80m', sa.Float(), nullable=False),
    sa.Column('wind_speed_120m', sa.Float(), nullable=False),
    sa.Column('wind_speed_180m', sa.Float(), nullable=False),
    sa.Column('wind_direction_10m', sa.Integer(), nullable=False),
    sa.Column('wind_direction_80m', sa.Integer(), nullable=False),
    sa.Column('wind_direction_120m', sa.Integer(), nullable=False),
    sa.Column('wind_direction_180m', sa.Integer(), nullable=False),
    sa.Column('hourly_measurement_context_id', sa.Integer(), nullable=True),
    sa.Column('inserted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hourly_measurement_context_id'], ['hourly_schema.hourly__measurement_context.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hourly_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hourly__wind_measurements', schema='hourly_schema')
    op.drop_table('hourly__visibility_measurements', schema='hourly_schema')
    op.drop_table('hourly__temperature_measurements', schema='hourly_schema')
    op.drop_table('hourly__soil_measurements', schema='hourly_schema')
    op.drop_table('hourly__percipitation_measurements', schema='hourly_schema')
    op.drop_table('hourly__measurement_context', schema='hourly_schema')
    # ### end Alembic commands ###
