"""fixed field and table name typos

Revision ID: 75be485490a5
Revises: 9c63720f4bcc
Create Date: 2025-07-15 09:49:52.598068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75be485490a5'
down_revision: Union[str, None] = '9c63720f4bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hourly__precipitation_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('precipitation', sa.Float(), nullable=False),
    sa.Column('precipitation_probability', sa.Integer(), nullable=False),
    sa.Column('relative_humidity_2m', sa.Integer(), nullable=False),
    sa.Column('hourly_measurement_context_id', sa.Integer(), nullable=True),
    sa.Column('inserted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hourly_measurement_context_id'], ['hourly_schema.hourly__measurement_context.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hourly_schema'
    )
    op.drop_table('hourly__percipitation_measurements', schema='hourly_schema')
    op.add_column('raw__daily_metrics', sa.Column('precipatition_hours_in_h', sa.Float(), nullable=False), schema='raw_schema')
    op.drop_column('raw__daily_metrics', 'precipatition_hours_in_s', schema='raw_schema')
    op.add_column('raw__hourly_metrics', sa.Column('precipitation_in_mm', sa.Float(), nullable=False), schema='raw_schema')
    op.add_column('raw__hourly_metrics', sa.Column('precipitation_probability_in_percentage', sa.Integer(), nullable=False), schema='raw_schema')
    op.drop_column('raw__hourly_metrics', 'percipitation_probability_in_percentage', schema='raw_schema')
    op.drop_column('raw__hourly_metrics', 'percipitation_in_mm', schema='raw_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw__hourly_metrics', sa.Column('percipitation_in_mm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False), schema='raw_schema')
    op.add_column('raw__hourly_metrics', sa.Column('percipitation_probability_in_percentage', sa.INTEGER(), autoincrement=False, nullable=False), schema='raw_schema')
    op.drop_column('raw__hourly_metrics', 'precipitation_probability_in_percentage', schema='raw_schema')
    op.drop_column('raw__hourly_metrics', 'precipitation_in_mm', schema='raw_schema')
    op.add_column('raw__daily_metrics', sa.Column('precipatition_hours_in_s', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False), schema='raw_schema')
    op.drop_column('raw__daily_metrics', 'precipatition_hours_in_h', schema='raw_schema')
    op.create_table('hourly__percipitation_measurements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('percipitation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('percipitation_probability', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('relative_humidity_2m', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hourly_measurement_context_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hourly_measurement_context_id'], ['hourly_schema.hourly__measurement_context.id'], name='hourly__percipitation_measure_hourly_measurement_context_i_fkey'),
    sa.PrimaryKeyConstraint('id', name='hourly__percipitation_measurements_pkey'),
    schema='hourly_schema'
    )
    op.drop_table('hourly__precipitation_measurements', schema='hourly_schema')
    # ### end Alembic commands ###
