"""Add util zone

Revision ID: 9c63720f4bcc
Revises: b4f7bed26057
Create Date: 2025-07-07 13:59:59.702400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c63720f4bcc'
down_revision: Union[str, None] = 'b4f7bed26057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS util_schema")
    op.create_table(
        'update_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('data_type', sa.String(), nullable=False),
        sa.Column('last_updated', sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint("data_type IN ('hourly', 'daily')", name='check_data_type'),
        sa.UniqueConstraint('data_type', name='uq_data_type'),
        schema='util_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update_log',schema='util_schema')
    # ### end Alembic commands ###
