"""Add raw__hourly_metrics table to database

Revision ID: aac566e288dc
Revises: 6c8aa5adf29d
Create Date: 2025-06-20 13:42:47.395673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac566e288dc'
down_revision: Union[str, None] = '6c8aa5adf29d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw__hourly_metrics',
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('measurements_date_and_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('temperature_2m_in_C', sa.Float(), nullable=False),
    sa.Column('temperature_80m_in_C', sa.Float(), nullable=False),
    sa.Column('temperature_120m_in_C', sa.Float(), nullable=False),
    sa.Column('temperature_180m_in_C', sa.Float(), nullable=False),
    sa.Column('relative_humidity_2m_in_percentage', sa.Integer(), nullable=False),
    sa.Column('percipitation_in_mm', sa.Float(), nullable=False),
    sa.Column('percipitation_probability_in_percentage', sa.Integer(), nullable=False),
    sa.Column('cloud_cover_low_in_percentage', sa.Integer(), nullable=False),
    sa.Column('cloud_cover_in_percentage', sa.Integer(), nullable=False),
    sa.Column('cloud_cover_mid_in_percentage', sa.Integer(), nullable=False),
    sa.Column('cloud_cover_high_in_percentage', sa.Integer(), nullable=False),
    sa.Column('visibility_in_m', sa.Integer(), nullable=False),
    sa.Column('wind_speed_10m_in_kmph', sa.Float(), nullable=False),
    sa.Column('wind_speed_80m_in_kmph', sa.Float(), nullable=False),
    sa.Column('wind_speed_120m_in_kmph', sa.Float(), nullable=False),
    sa.Column('wind_speed_180m_in_kmph', sa.Float(), nullable=False),
    sa.Column('wind_direction_10m_in_degree', sa.Integer(), nullable=False),
    sa.Column('wind_direction_80m_in_degree', sa.Integer(), nullable=False),
    sa.Column('wind_direction_120m_in_degree', sa.Integer(), nullable=False),
    sa.Column('wind_direction_180m_in_degree', sa.Integer(), nullable=False),
    sa.Column('soil_temperature_0cm_in_C', sa.Float(), nullable=False),
    sa.Column('soil_temperature_6cm_in_C', sa.Float(), nullable=False),
    sa.Column('soil_temperature_18cm_in_C', sa.Float(), nullable=False),
    sa.Column('soil_temperature_54cm_in_C', sa.Float(), nullable=False),
    sa.Column('soil_moisture_0cm_to_1cm_in_percentage', sa.Float(), nullable=False),
    sa.Column('soil_moisture_1cm_to_3cm_in_percentage', sa.Float(), nullable=False),
    sa.Column('soil_moisture_3cm_to_9cm_in_percentage', sa.Float(), nullable=False),
    sa.Column('soil_moisture_9cm_to_27cm_in_percentage', sa.Float(), nullable=False),
    sa.Column('soil_moisture_27cm_to_81cm_in_percentage', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('longitude', 'latitude', 'measurements_date_and_time'),
    schema='raw_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw__hourly_metrics', schema='raw_schema')
    # ### end Alembic commands ###
