"""Add util schema

Revision ID: b4f7bed26057
Revises: aac566e288dc
Create Date: 2025-07-07 13:54:46.034766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4f7bed26057'
down_revision: Union[str, None] = 'aac566e288dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw__hourly_metrics', sa.Column('inserted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False), schema='raw_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw__hourly_metrics', 'inserted_at', schema='raw_schema')
    # ### end Alembic commands ###
